apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata: { name: aguda-provider, annotations: { argocd.argoproj.io/sync-wave: "20" } }
spec:
  provider:
    gcpsm:
      projectID: "${GCP_PROJECT_ID}"
      auth:
        workloadIdentity:
          clusterLocation: "${GCP_CLUSTER_LOCATION}"
          clusterName: "${GCP_CLUSTER_NAME}"
          serviceAccountRef: { name: aguda-secrets, namespace: "aguda-${ENVIRONMENT}" }
