apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../../validation-policies.yaml]
patches:
  - target: { kind: ClusterPolicy }
    patch: |-
      - op: replace
        path: /spec/validationFailureAction
        value: Audit
