// feature-10022026-Maurice: authenticated checkout UI. Payment Element mounts at the provider seam; card data stays with Stripe.
"use client"
import { FormEvent, useEffect, useState } from "react"
import { trace } from "../../observability/trace"

type Contract = { payment?: { clientSecret?: string; paymentIntentId?: string; publishableKey?: string; status?: string }; shipping?: { name: string; amount: number }; tax_total?: number }
const options = [{ id: "aguda-ph-standard", label: "PH standard — ₱150", country: "ph" }, { id: "aguda-ph-express", label: "PH express — ₱300", country: "ph" }, { id: "aguda-us-standard", label: "US standard — $25", country: "us" }]

export default function CheckoutPage() {
  const [signedIn, setSignedIn] = useState<boolean | null>(null); const [cartId, setCartId] = useState(""); const [country, setCountry] = useState<"ph" | "us">("ph"); const [contract, setContract] = useState<Contract | null>(null); const [message, setMessage] = useState(""); const [processing, setProcessing] = useState(false)
  useEffect(() => { void trace("checkout.session", async () => { if (new URLSearchParams(window.location.search).has("payment_return")) setMessage("Payment received by the browser; waiting for verified webhook confirmation…") ; const session = await fetch("/api/account/session", { credentials: "include" }); setSignedIn(session.ok); const response = await fetch("/api/cart", { credentials: "include" }); const cart = await response.json().catch(() => ({})) as { cart?: { id?: string } }; setCartId(cart.cart?.id ?? "") }) }, [])
  async function submit(event: FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); await trace("checkout.submit", async () => { setProcessing(true); setMessage("Processing payment…"); try { const data = new FormData(event.currentTarget); const response = await fetch("/api/checkout", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ cart_id: cartId, shipping_option_id: data.get("shipping_option_id"), amount: 0, currency_code: country === "ph" ? "php" : "usd", shipping_address: { first_name: data.get("first_name"), last_name: data.get("last_name"), address_1: data.get("address_1"), city: data.get("city"), postal_code: data.get("postal_code"), country_code: country } }) }); const payload = await response.json() as Contract & { message?: string }; if (!response.ok) throw new Error(payload.message ?? "Checkout could not be prepared."); setContract(payload); setMessage("Payment is ready. Confirm it with the provider Payment Element.") } catch (error) { setMessage(error instanceof Error ? error.message : "Checkout failed.") } finally { setProcessing(false) } }) }
  if (signedIn === null) return <main className="account-shell"><p role="status">Loading checkout…</p></main>
  if (!signedIn) return <main className="account-shell"><h1>Sign in to checkout</h1><p>Checkout is available to signed-in customers only.</p><a href="/account">Sign in</a></main>
  return <main className="account-shell"><h1>Checkout</h1><form onSubmit={(event) => void submit(event)}><label>First name<input name="first_name" required /></label><label>Last name<input name="last_name" required /></label><label>Address<input name="address_1" required /></label><label>City<input name="city" required /></label><label>Country<select value={country} onChange={(event) => setCountry(event.target.value as "ph" | "us")}><option value="ph">Philippines</option><option value="us">United States</option></select></label><label>Postal code<input name="postal_code" required /></label><fieldset><legend>Shipping</legend>{options.filter((option) => option.country === country).map((option) => <label key={option.id}><input type="radio" name="shipping_option_id" value={option.id} defaultChecked required />{option.label}</label>)}</fieldset><button type="submit" disabled={processing || !cartId}>{processing ? "Processing…" : "Continue to payment"}</button></form><p role="status" aria-live="polite">{message}</p>{contract?.payment?.clientSecret && <section aria-label="Payment Element contract"><p>Payment provider: Stripe Payment Element</p><p data-payment-intent={contract.payment.paymentIntentId}>Payment session prepared. Card fields are hosted by Stripe.</p><p>Tax: ₱0 / $0</p></section>}</main>
}
