// feature-10022026-Maurice: authenticated checkout UI. Payment Element mounts at the provider seam; card data stays with Stripe.
"use client"
import { FormEvent, useEffect, useState } from "react"
import { trace } from "../../observability/trace"
import { Button } from "../../components/ui"

type Contract = { payment?: { clientSecret?: string; paymentIntentId?: string; publishableKey?: string; status?: string }; shipping?: { name: string; amount: number }; tax_total?: number }
const options = [{ id: "aguda-ph-standard", label: "PH standard — ₱150", country: "ph" }, { id: "aguda-ph-express", label: "PH express — ₱300", country: "ph" }, { id: "aguda-us-standard", label: "US standard — $25", country: "us" }]

export default function CheckoutPage() {
  const [signedIn, setSignedIn] = useState<boolean | null>(null); const [cartId, setCartId] = useState(""); const [country, setCountry] = useState<"ph" | "us">("ph"); const [contract, setContract] = useState<Contract | null>(null); const [message, setMessage] = useState(""); const [processing, setProcessing] = useState(false)
  useEffect(() => { void trace("checkout.session", async () => { if (new URLSearchParams(window.location.search).has("payment_return")) setMessage("Payment received by the browser; waiting for verified webhook confirmation…") ; const session = await fetch("/api/account/session", { credentials: "include" }); setSignedIn(session.ok); const response = await fetch("/api/cart", { credentials: "include" }); const cart = await response.json().catch(() => ({})) as { cart?: { id?: string } }; setCartId(cart.cart?.id ?? "") }) }, [])
  async function submit(event: FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); await trace("checkout.submit", async () => { setProcessing(true); setMessage("Processing payment…"); try { const data = new FormData(event.currentTarget); const response = await fetch("/api/checkout", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ cart_id: cartId, shipping_option_id: data.get("shipping_option_id"), amount: 0, currency_code: country === "ph" ? "php" : "usd", shipping_address: { first_name: data.get("first_name"), last_name: data.get("last_name"), address_1: data.get("address_1"), city: data.get("city"), postal_code: data.get("postal_code"), country_code: country } }) }); const payload = await response.json() as Contract & { message?: string }; if (!response.ok) throw new Error(payload.message ?? "Checkout could not be prepared."); setContract(payload); setMessage("Payment is ready. Confirm it with the provider Payment Element.") } catch (error) { setMessage(error instanceof Error ? error.message : "Checkout failed.") } finally { setProcessing(false) } }) }
  if (signedIn === null) return <main id="main-content" className="account-shell"><p role="status">Loading checkout…</p></main>
  if (!signedIn) return <main id="main-content" className="account-shell"><h1>Sign in to checkout</h1><p>Checkout is available to signed-in customers only.</p><a className="button" href="/account">Sign in</a></main>
  return <main id="main-content" className="account-shell"><p className="eyebrow">Sheet 03 / payment preparation</p><h1>Checkout</h1><form onSubmit={(event) => void submit(event)}><div id="checkout-errors" className={message && !contract ? "summary-error" : "summary-error"} hidden={!message || Boolean(contract)}><strong>Checkout needs attention.</strong><p>{message}</p></div><label htmlFor="first-name">First name<input id="first-name" name="first_name" autoComplete="given-name" required /></label><label htmlFor="last-name">Last name<input id="last-name" name="last_name" autoComplete="family-name" required /></label><label htmlFor="address">Address<input id="address" name="address_1" autoComplete="street-address" required /></label><label htmlFor="city">City<input id="city" name="city" autoComplete="address-level2" required /></label><label htmlFor="country">Country<select id="country" value={country} onChange={(event) => setCountry(event.target.value as "ph" | "us")}><option value="ph">Philippines</option><option value="us">United States</option></select></label><label htmlFor="postal-code">Postal code<input id="postal-code" name="postal_code" autoComplete="postal-code" required /></label><fieldset><legend>Shipping method</legend>{options.filter((option) => option.country === country).map((option) => <label key={option.id}><input type="radio" name="shipping_option_id" value={option.id} defaultChecked required />{option.label}</label>)}</fieldset><Button type="submit" disabled={processing || !cartId}>{processing ? "Processing…" : "Continue to payment"}</Button></form><p role="status" aria-live="polite">{message}</p>{contract?.payment?.clientSecret && <section className="order-card" aria-label="Payment Element contract"><p className="eyebrow">Payment session prepared</p><p>Payment fields are hosted securely by Stripe. Your card details never touch this store.</p><p data-payment-intent={contract.payment.paymentIntentId} className="utility">Provider session ready · Tax: ₱0 / $0</p><a className="button" href="/checkout/confirmation">Check order status</a></section>}</main>
}
